### ISSUE TITLE
Is it possible to implement Opus as a codec?

### ISSUE THREAD

**Issue by 96AA48** [Rantanen/node-mumble#39]
I've been trying to create a mumble bot that streams music to the server, only the stream (celt) seems to corrupt every now and again, stopping or just turning into straight robot voice. Any chance you might implement Opus?

**Comment by Prior99** [comment]
Opus is already implemented, make sure your server and all clients in the channel have it enabled.

**Comment by 96AA48** [comment]
It will automatically switch to the Opus codec when all of the clients have it enabled? Or do I need to pass some extra options to something?

**Comment by Prior99** [comment]
No it will automatically select it then. Check the information of your server and connected clients to figure whether opus is used or not.

**Comment by 96AA48** [comment]
I've forced opus on my server as well as in the code but didn't notice a
change in quality or reliability, it still cuts out and the audio has the
same quality as if I was streaming with celt.

**Comment by Prior99** [comment]
I am not sure if you can improve the quality any further. One option would be to set the maximum bandwidth of the server. I have set the maximum bandwidth to an insane high value but did not really experience a gain in quality when streaming music.

Keep in mind that both celt and opus are optimized for realtime transmission of voice data with a delay as low as possible, not quality!

You will never achieve a quality similiar to any livestream method such as for example http livestreaming which has a delay of multiple seconds.

As for the cutouts: I also have those from time to time but I could eliminate them mostly when reducing the amount of computation needed for each frame as much as possible:

 * When ever possible, try to pipe the raw audio directly to mumble by using .pipe()
 * Prepare the data before transmitting it, do not decode live, decode the file before, long computations could cause these cutouts
 * If you still have to do live computations do them in C in a native addon rather than in javascript, parallelize them
 * Lower the quality of certain transcoding operations such as samplerate conversion or even better: Also do those beforehand
 * Avoid reading from directly from disk, buffer your data
 * Make sure the network connection from the bot to the server is good or even better: Run the bot on the same server as the mumble server and connect via localhost
 * Avoid mixing multiple streams, use only one stream at the time

**Comment by Prior99** [comment]
You could also have a look on how I did it here: https://git.cronosx.de/prior/mumble-bot/tree/master This is still work in progress but the music streaming does work smoothly.

**Comment by 96AA48** [comment]
Dude, thanks a lot! I've never seen someone this dedicated to helping someone out on Github! Thanks again!

**Comment by Prior99** [comment]
No problem. Have fun :)

**Comment by Flet** [comment]
@Prior99 cool repo! I wish I could star it :)

**Comment by Prior99** [comment]
@Flet thank you. Maybe I can migrate it to Github if anyone is interested - currently the bot dies when a user diaconnects ^^

**Comment by Prior99** [comment]
Here you go: [Prior99/mumble-bot](https://github.com/Prior99/mumble-bot/tree/master). I will be awaiting your contributions :)

**Comment by Prior99** [comment]
@Rantanen  This issue can be closed.

**Comment by Rantanen** [comment]
Good point!
