### ISSUE TITLE
how to self mute / self deaf?

### ISSUE THREAD

**Issue by Jrawke** [Rantanen/node-mumble#73]
Hello,

Sorry for the basic question, but what is the API call for self muting / self deafening? I couldn't find it in the wiki...

Thanks

**Comment by Jrawke** [comment]
If the API is missing, I'd be willing to add it. I imagine it should go in MumbleClient.js, by inserting member functions selfMute() and selfDeaf()

**Comment by Rantanen** [comment]
The API seems to be missing.

Despite the fact that I don't think you can self mute other people, I'd still say it should go to the [`User`](https://github.com/Rantanen/node-mumble/blob/master/lib/User.js) object. `client.user.selfMute()` isn't that much worse compared to `client.selfMute()` and it would help keeping the `MumbleConnection` interface cleaner.

The implementation should be simple enough. You need to construct a [`UserState`](https://github.com/mumble-voip/mumble/blob/master/src/Mumble.proto#L158) protocol buffer message and send it to the server. The `UserState` has `self_mute` and `self_deaf` fields. Identify the user with the `session` field. I believe you can leave the `user_id` empty (as that might be null anyway if the connection isn't registered).

In the `User` context the protocol buffer messages are sent with `this.client.connection.sendMessage()`. You can check the [`joinChannel()`](https://github.com/Rantanen/node-mumble/blob/master/lib/User.js#L33) for an example of its usage.

Think the methods should be named `setSelfDeaf( boolean )` and `setSelfMute( boolean )`. The read-operations can still be done using `user.selfDeaf` field. I believe we'd also need a `set( object )` method for setting multiple flags at the same time, ie:

```javascript
client.user.set({ selfDeaf: true, selfMute: true });  // "User was muted and deafened"
```

Otherwise the mumble server would probably end up reporting "User X is deafened" "User X is muted" instead of "User X is muted and deafened".

**Comment by Rantanen** [comment]
Oh. And given the case of the `set` method, I'm now convinced that it should go to the `User` object and not the `MumbleClient`. Otherwise we'd need the `set` on the client or then we'd need to bypass it (in this case) with: `setSelfMute`, `setSelfDeaf`, `setSelfMuteAndDeaf` which is a recipe for disaster in the long run if we get more of these flags that affect only the current user. :)

**Comment by Jrawke** [comment]
Thanks for the quick and informative response. I'd like to add this functionality (you can assign me to this issue if you'd like). I'll try to do it over the weekend, you'll get a pull request when I get around to it

**Comment by tjhorner** [comment]
boop. check 2e3a13b96b65d8ec1593a50fdaf98252bad9f243

**Comment by Jrawke** [comment]
Less work for me :)

**Comment by tjhorner** [comment]
ye. I just did that in the browser in a minute or so lol
