### ISSUE TITLE
v8 warning for native addon on node v6+

### ISSUE THREAD

**Issue by notthetup** [Rantanen/node-mumble#92]
When requiring "mumble", on nodejs v6+, there is a warning from v8 about usage of deprecated APIs. Not sure if this is an node-mumble issue or from one of it's dependencies. I do see mention of both `celt` and `jitterbuffer` in the [stacktrace.txt](https://github.com/Rantanen/node-mumble/files/405037/stacktrace.txt)

```
[21:42]chinmay@rayleigh: ❯ node --version
v6.3.1
[21:42]chinmay@rayleigh: ❯ node -e 'require("mumble")'
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.
```

**Comment by tjhorner** [comment]
There isn't anything that compiles here, so it's probably one of those.

**Comment by Prior99** [comment]
Bump! Same Problem here. 
Also with v4.4.5 I get 'Error: Module version mismatch. Expected 46, got 48.'
Which version of node are we supposed to use?

**Comment by Rantanen** [comment]
I'd guess the Module version mismatch is caused by upgrading Node version without rebuilding the packages.

Try removing the node_packages and doing npm install. I'm expecting that to solve the Error.

The warning will still be there. I think it's caused by `node-jitterbuffer` - but I had trouble building and running that with `node-gyp` for some reason. I'll take a look at it again soon.

**Comment by Rantanen** [comment]
Found the issue in node-jitterbuffer. Fixed it there (and in node-celt).
